// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Model.Models;
using System;
using System.Collections.Generic;

namespace Model.Models.Configurations
{
    public partial class ContratoConfiguration : IEntityTypeConfiguration<Contrato>
    {
        public void Configure(EntityTypeBuilder<Contrato> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK__contrato__3213E83FD5201CCE");

            entity.ToTable("contrato");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.FechaContrato)
            .HasColumnType("date")
            .HasColumnName("fecha_contrato");
            entity.Property(e => e.SalarioJugador)
            .HasColumnType("decimal(10, 2)")
            .HasColumnName("salario_jugador");
            entity.Property(e => e.UsuEquipoId).HasColumnName("usu_equipo_id");
            entity.Property(e => e.UsuJugadorId).HasColumnName("usu_jugador_id");

            entity.HasOne(d => d.UsuEquipo).WithMany(p => p.ContratoUsuEquipo)
            .HasForeignKey(d => d.UsuEquipoId)
            .HasConstraintName("FK__contrato__usu_eq__30C33EC3");

            entity.HasOne(d => d.UsuJugador).WithMany(p => p.ContratoUsuJugador)
            .HasForeignKey(d => d.UsuJugadorId)
            .HasConstraintName("FK__contrato__usu_ju__31B762FC");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Contrato> entity);
    }
}
