// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Model.Models;
using System;
using System.Collections.Generic;

namespace Model.Models.Configurations
{
    public partial class EquipoConfiguration : IEntityTypeConfiguration<Equipo>
    {
        public void Configure(EntityTypeBuilder<Equipo> entity)
        {
            entity.HasKey(e => e.EquipoId).HasName("PK__Equipo__DE8A0BFF0D2335C5");

            entity.Property(e => e.EquipoId)
            .ValueGeneratedNever()
            .HasColumnName("EquipoID");
            entity.Property(e => e.Nombre).HasMaxLength(100);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Equipo> entity);
    }
}
