// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Model.Models;
using System;
using System.Collections.Generic;

namespace Model.Models.Configurations
{
    public partial class MensajeConfiguration : IEntityTypeConfiguration<Mensaje>
    {
        public void Configure(EntityTypeBuilder<Mensaje> entity)
        {
            entity.HasKey(e => e.MensajeId).HasName("PK__Mensaje__FEA0557FA6CA8BE5");

            entity.Property(e => e.MensajeId).HasColumnName("MensajeID");
            entity.Property(e => e.DestinatarioId).HasColumnName("DestinatarioID");
            entity.Property(e => e.FechaEnvio).HasColumnType("datetime");
            entity.Property(e => e.RemitenteId).HasColumnName("RemitenteID");

            entity.HasOne(d => d.Destinatario).WithMany(p => p.Mensaje)
            .HasForeignKey(d => d.DestinatarioId)
            .HasConstraintName("FK__Mensaje__Destina__5EBF139D");

            entity.HasOne(d => d.Remitente).WithMany(p => p.Mensaje)
            .HasForeignKey(d => d.RemitenteId)
            .HasConstraintName("FK__Mensaje__Remiten__5DCAEF64");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Mensaje> entity);
    }
}
