// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Model.Models;
using System;
using System.Collections.Generic;

namespace Model.Models.Configurations
{
    public partial class PostulacionConfiguration : IEntityTypeConfiguration<Postulacion>
    {
        public void Configure(EntityTypeBuilder<Postulacion> entity)
        {
            entity.HasKey(e => e.Idpostulacion).HasName("PK__postulac__0C7D09DCA454C8A7");

            entity.ToTable("postulacion");

            entity.Property(e => e.Idpostulacion).HasColumnName("idpostulacion");
            entity.Property(e => e.FechaPostulacion)
            .HasColumnType("date")
            .HasColumnName("fecha_postulacion");
            entity.Property(e => e.PostuEquipoId).HasColumnName("Postu_Equipo_id");
            entity.Property(e => e.PostuJugadorId).HasColumnName("Postu_jugador_id");

            entity.HasOne(d => d.PostuEquipo).WithMany(p => p.Postulacion)
            .HasForeignKey(d => d.PostuEquipoId)
            .HasConstraintName("FK_postulacion_Equipo");

            entity.HasOne(d => d.PostuJugador).WithMany(p => p.Postulacion)
            .HasForeignKey(d => d.PostuJugadorId)
            .HasConstraintName("FK__postulaci__usu_j__440B1D61");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Postulacion> entity);
    }
}
