// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Model.Models;
using System;
using System.Collections.Generic;

namespace Model.Models.Configurations
{
    public partial class PostulacionConfiguration : IEntityTypeConfiguration<Postulacion>
    {
        public void Configure(EntityTypeBuilder<Postulacion> entity)
        {
            entity.HasKey(e => e.Idpostulacion).HasName("PK__postulac__0C7D09DCB613370C");

            entity.ToTable("postulacion");

            entity.Property(e => e.Idpostulacion).HasColumnName("idpostulacion");
            entity.Property(e => e.FechaPostulacion)
            .HasColumnType("date")
            .HasColumnName("fecha_postulacion");
            entity.Property(e => e.UsuEquipoId).HasColumnName("usu_equipo_id");
            entity.Property(e => e.UsuJugadorId).HasColumnName("usu_jugador_id");

            entity.HasOne(d => d.UsuEquipo).WithMany(p => p.PostulacionUsuEquipo)
            .HasForeignKey(d => d.UsuEquipoId)
            .HasConstraintName("FK__postulaci__usu_e__3493CFA7");

            entity.HasOne(d => d.UsuJugador).WithMany(p => p.PostulacionUsuJugador)
            .HasForeignKey(d => d.UsuJugadorId)
            .HasConstraintName("FK__postulaci__usu_j__3587F3E0");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Postulacion> entity);
    }
}
