// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Model.Models;
using System;
using System.Collections.Generic;

namespace Model.Models.Configurations
{
    public partial class PostulacionConfiguration : IEntityTypeConfiguration<Postulacion>
    {
        public void Configure(EntityTypeBuilder<Postulacion> entity)
        {
            entity.HasKey(e => e.PostulacionId).HasName("PK__Postulac__5F6D89499F12E94A");

            entity.Property(e => e.PostulacionId).HasColumnName("PostulacionID");
            entity.Property(e => e.FechaPostulacion).HasColumnType("date");
            entity.Property(e => e.Idequipo).HasColumnName("IDEquipo");
            entity.Property(e => e.Idjugador).HasColumnName("IDJugador");

            entity.HasOne(d => d.IdequipoNavigation).WithMany(p => p.Postulacion)
            .HasForeignKey(d => d.Idequipo)
            .HasConstraintName("FK_Equipo_Postulacion");

            entity.HasOne(d => d.IdjugadorNavigation).WithMany(p => p.Postulacion)
            .HasForeignKey(d => d.Idjugador)
            .HasConstraintName("FK_Jugador_Postulacion");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Postulacion> entity);
    }
}
