// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Model.Models;
using System;
using System.Collections.Generic;

namespace Model.Models.Configurations
{
    public partial class UsuariosConfiguration : IEntityTypeConfiguration<Usuarios>
    {
        public void Configure(EntityTypeBuilder<Usuarios> entity)
        {
            entity.HasKey(e => e.UsuarioId).HasName("PK__Usuarios__2B3DE798BFBD0921");

            entity.Property(e => e.UsuarioId).HasColumnName("UsuarioID");
            entity.Property(e => e.Contrasenia).HasMaxLength(255);
            entity.Property(e => e.Email).HasMaxLength(255);
            entity.Property(e => e.FechaNacimiento).HasColumnType("date");
            entity.Property(e => e.NombreApellido)
            .HasMaxLength(100)
            .HasColumnName("Nombre_Apellido");
            entity.Property(e => e.Posicion)
            .HasMaxLength(50)
            .IsUnicode(false);
            entity.Property(e => e.Rol).HasDefaultValueSql("((2))");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Usuarios> entity);
    }
}
