// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Model.Models;

public partial class Contrato
{
    public int Id { get; set; }

    public decimal? SalarioJugador { get; set; }

    public DateTime? FechaContrato { get; set; }

    public int? ContEquipoid { get; set; }

    public int? ContUserid { get; set; }

    public string CategoriaEquipo { get; set; }

    public virtual Equipo ContEquipo { get; set; }

    public virtual Usuarios ContUser { get; set; }
}