// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Model.Models;

public partial class Equipo
{
    public int EquipoId { get; set; }

    public int? UsuarioId { get; set; }

    public string Nombre { get; set; }

    public string Descripcion { get; set; }

    public string PosiciónRequerida { get; set; }

    public int? JugadorId { get; set; }

    public virtual ICollection<Contrato> Contrato { get; set; } = new List<Contrato>();

    public virtual Jugador Jugador { get; set; }

    public virtual Usuarios Usuario { get; set; }
}