// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Model.Models.Configurations;
using System;
using System.Collections.Generic;
#nullable disable

namespace Model.Models;

public partial class FindYourClubContext : DbContext
{
    public FindYourClubContext(DbContextOptions<FindYourClubContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Contrato> Contrato { get; set; }

    public virtual DbSet<Equipo> Equipo { get; set; }

    public virtual DbSet<Postulacion> Postulacion { get; set; }

    public virtual DbSet<Usuarios> Usuarios { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.ApplyConfiguration(new Configurations.ContratoConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.EquipoConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.PostulacionConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.UsuariosConfiguration());

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}
