// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Model.Models;

public partial class Jugador
{
    public int JugadorId { get; set; }

    public string Nombre { get; set; }

    public string Apellido { get; set; }

    public string Descripcion { get; set; }

    public string Posicion { get; set; }

    public int? UsuarioId { get; set; }

    public virtual Usuarios Usuario { get; set; }

    public virtual ICollection<Equipo> Equipo { get; set; } = new List<Equipo>();
}