// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Model.Models;

public partial class Mensaje
{
    public int MensajeId { get; set; }

    public int? RemitenteId { get; set; }

    public int? DestinatarioId { get; set; }

    public string Contenido { get; set; }

    public DateTime? FechaEnvio { get; set; }

    public virtual Equipo Destinatario { get; set; }

    public virtual Jugador Remitente { get; set; }
}