// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Model.Models;

public partial class Postulacion
{
    public int Idpostulacion { get; set; }

    public DateTime? FechaPostulacion { get; set; }

    public int? PostuJugadorId { get; set; }

    public int? PostuEquipoId { get; set; }

    public virtual Equipo PostuEquipo { get; set; }

    public virtual Usuarios PostuJugador { get; set; }
}