// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Model.Models;

public partial class Postulacion
{
    public int PostulacionId { get; set; }

    public DateTime? FechaPostulacion { get; set; }

    public int? Idjugador { get; set; }

    public int? Idequipo { get; set; }

    public virtual Equipo IdequipoNavigation { get; set; }

    public virtual Jugador IdjugadorNavigation { get; set; }
}