// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Model.Models;

public partial class Postulacion
{
    public int Idpostulacion { get; set; }

    public DateTime? FechaPostulacion { get; set; }

    public int? UsuEquipoId { get; set; }

    public int? UsuJugadorId { get; set; }

    public virtual Usuarios UsuEquipo { get; set; }

    public virtual Usuarios UsuJugador { get; set; }
}